import { Project } from '@/types/project';

export const projects: Project[] = [
  {
    title: 'Monolog',
    description:
      'A minimalistic periodic accountability app to keep you accountable to your life, work, and progress. Track your goals, reflect on your journey, and maintain consistent momentum through simple, meaningful check-ins.',
    image: '/assets/monolog.svg',
    link: '#',
    technologies: [
      'React Native',
      'Swift',
      'SwiftUI',
      'Expo',
      'Firebase',
      'NativeWind',
    ],
    features: [
      'Periodic check-ins for life, work, and personal goals',
      'Minimalistic design focused on clarity and simplicity',
      'Progress tracking and reflection prompts',
      'Customizable accountability schedules',
      'Visual timeline of your growth and achievements',
      'Private journaling with optional goal sharing',
    ],
    github: 'https://github.com/spandan-mozumder/monolog',
    live: '#',
    details: false,
    isWorking: true,
  },
  {
    title: 'DevOmegle',
    description:
      'A socializing platform like Omegle but filtered exclusively for developers. Connect with other devs, share ideas, collaborate on projects, and network with like-minded programmers.',
    image: '/assets/devomegleImg.png',
    link: 'https://devomegle.spandyz.xyz',
    technologies: [
      'Next.js',
      'TypeScript',
      'WebSocket',
      'Tailwind CSS',
      'PostgreSQL',
      'Prisma',
    ],
    features: [
      'Real-time video and text chat with developers',
      'Developer-focused filtering and matching',
      'GitHub integration for profile verification',
      'Interest-based matching (tech stack, experience level)',
      'Code sharing and collaboration features',
    ],
    github: 'https://github.com/spandan-mozumder/devomegle',
    live: 'https://devomegle.spandyz.xyz',
    details: false,
    isWorking: true,
  },
  {
    title: 'AstraTrade',
    description:
      'A multichain paper trading platform on DEX. Practice trading across multiple blockchain networks with virtual funds, learn DeFi strategies, and track your performance without risking real assets.',
    image: '/assets/astratradeImg.png',
    link: 'https://astratrade-client.vercel.app/',
    technologies: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'PostgreSQL',
      'Prisma',
    ],
    features: [
      'Multichain support across major DEX networks',
      'Virtual portfolio management',
      'Real-time price tracking and charts',
      'Trading strategy backtesting',
      'Performance analytics and leaderboards',
      'Learn DeFi without financial risk',
    ],
    github: 'https://github.com/spandan-mozumder/astratrade',
    live: 'https://astratrade-client.vercel.app/',
    details: false,
    isWorking: true,
  },
  {
    title: 'GitWit',
    description:
      'An AI-based agent that helps young developers understand codebases easily. It fetches the entire codebase, summarizes files, summarizes commits, and provides a chatbot to answer questions about the repository.',
    image: '/assets/gitwitImg.png',
    link: 'https://git-wit-five.vercel.app/',
    technologies: [
      'Next.js',
      'TypeScript',
      'Prisma',
      'tRPC',
      'shadcn/ui',
      'Gemini',
      'AssemblyAI',
      'PostgreSQL',
      'Tailwind CSS',
      'Clerk',
      'Supabase',
      'Octokit',
      'Langchain',
    ],
    features: [
      'AI‑powered code reviews with security checks and code quality analysis',
      'Live GitHub analytics with DORA metrics and risk scoring',
      'Team collab chat with syntax highlighting and attachments',
      'Meeting transcription with auto action items',
      'Security scanning for eval(), hardcoded creds, API keys',
      'RAG docs with Langchain + Supabase vectors',
      'Velocity insights, shortcuts, dark/light mode',
    ],
    github: 'https://github.com/spandan-mozumder/git-wit',
    live: 'https://git-wit-five.vercel.app/',
    details: false,
    isWorking: true,
  },
  {
    title: 'Fluxon',
    description:
      'Visual Workflow Automation Platform for building, running, and monitoring integrations and automations with a visual node editor, durable execution, and realtime observability.',
    image: '/assets/fluxonImg.png',
    link: 'https://fluxon-mu.vercel.app',
    technologies: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Prisma',
      'PostgreSQL',
      'Inngest',
      'tRPC',
      'ReactFlow',
      'WebSocket',
    ],
    features: [
      'Visual node‑based workflow editor with drag‑and‑drop nodes, connections, and reusable node types',
      'Triggers: Manual, Webhook, Google Forms, Stripe; Actions: HTTP Request, Discord, Slack, Gemini AI',
      'Durable background execution powered by Inngest with retries, step tracing, and execution history',
      'Real‑time execution status & node‑level progress via realtime channels and Inngest Realtime',
      'Type‑safe API surface with tRPC and full DB modeling via Prisma',
      'Credential management, per‑user workflows, and audit logs for secure automation',
      'Extensible node executors enabling custom integrations and AI‑powered nodes',
    ],
    github: 'https://github.com/spandan-mozumder/Fluxon',
    live: 'https://fluxon-mu.vercel.app',
    details: false,
    isWorking: true,
  },
  {
    title: 'Nexus Platform',
    description:
      'A comprehensive productivity platform that integrates project management, task boards, whiteboarding, documentation, and team communication into one seamless application.',
    image: '/assets/nexusImg.png',
    link: 'https://nexus-lyart-chi.vercel.app/',
    technologies: [
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Node.js',
      'PostgreSQL',
      'WebSocket',
      'Prisma',
      'Next.js',
    ],
    features: [
      'Kanban, Calendar, Table views with custom statuses and sprints',
      'Infinite canvas whiteboard with multiplayer cursors',
      'Drawing tools, notes, hierarchical docs with rich editor and covers',
      'Channels, DMs, threads, reactions, real‑time messaging',
      'Labels, priorities, analytics dashboard, public sharing',
    ],
    github: 'https://github.com/spandan-mozumder/nexus',
    live: 'https://nexus-lyart-chi.vercel.app/',
    details: false,
    isWorking: true,
  },
  {
    title: 'OctoScrape',
    description:
      'A powerful, visual workflow automation platform for web scraping and data extraction. Build complex scraping workflows through an intuitive drag-and-drop interface without writing any code.',
    image: '/assets/octoscrapeImg.png',
    link: 'https://octo-scrape.vercel.app/',
    technologies: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'shadcn/ui',
      'ReactFlow',
      'Prisma',
      'PostgreSQL',
      'Clerk',
      'Puppeteer',
      'Cheerio',
      'TanStack Query',
      'Recharts',
    ],
    features: [
      'ReactFlow builder with validations and conditional logic',
      'Browser automation, export to JSON/CSV, webhooks',
      'AES‑256 credential security, RBAC via Clerk',
      'Execution monitoring, performance analytics, charts',
      'Scheduling with on‑demand and cron',
      'Responsive UI, dark mode, sandboxed execution',
    ],
    github: 'https://github.com/spandan-mozumder/octo-scrape',
    live: 'https://octo-scrape.vercel.app/',
    details: false,
    isWorking: true,
  },
];

export const inDevelopmentProjects: Project[] = [];
